# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c2902b50caed1d4bf816f19be50c4ff2"
name = "selleasy-upsell-crosell-1"
handle = "selleasy-upsell-crosell-1"
application_url = "https://sussex-lung-therapeutic-war.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_products,read_themes,write_customers,write_draft_orders,write_markets,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://sussex-lung-therapeutic-war.trycloudflare.com/auth/callback",
  "https://sussex-lung-therapeutic-war.trycloudflare.com/auth/shopify/callback",
  "https://sussex-lung-therapeutic-war.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
