# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5045fae69d21ceaade75222335f45840"
name = "selleasy-upsell-crosell"
handle = "selleasy-upsell-crosell"
application_url = "https://herbs-stopping-arguments-maiden.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_products,read_themes,write_customers,write_draft_orders,write_markets,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://herbs-stopping-arguments-maiden.trycloudflare.com/auth/callback",
  "https://herbs-stopping-arguments-maiden.trycloudflare.com/auth/shopify/callback",
  "https://herbs-stopping-arguments-maiden.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
